baseURL = 'https://charaninfra.xyz/'
languageCode = 'en-us'
title = 'My Portfolio & Blog'
theme = 'PaperMod'
publishDir = "public"



[params.homeInfoParams]
  Title = "Hi, I'm Your Name 👋"
  Content = "Welcome to my portfolio and learning blog. I write about my career, projects, and personal learnings."

[[menu.main]]
  name = "Blog"
  url = "/posts/"
  weight = 10

[[menu.main]]
  name = "Portfolio"
  url = "/portfolio/"
  weight = 20

  [outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML", "RSS"]

